In [19]:
import numpy as np
a = (np.array([[2,1,1], [1,2,3]]))
b = np.ones_like(a)
b
c = np.ones(a.shape)
c = np.full((3, 4), 123)
c
d = np.eye(4)

In [20]:
a = np.array(['1.2', '2.3'])
a.astype(np.float32)

array([1.2, 2.3], dtype=float32)

In [22]:
a.astype(float).dtype

dtype('float64')

In [23]:
#slicing is not a copy

In [28]:
data = np.random.randn(7, 4)
data[data<0].ndim

1

In [32]:
arr = np.arange(49).reshape((7, 7))
arr


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [35]:
b = arr.cumsum(axis = 0)

In [36]:
np.save('b.npy', b)

In [37]:
np.load('b.npy')

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   9,  11,  13,  15,  17,  19],
       [ 21,  24,  27,  30,  33,  36,  39],
       [ 42,  46,  50,  54,  58,  62,  66],
       [ 70,  75,  80,  85,  90,  95, 100],
       [105, 111, 117, 123, 129, 135, 141],
       [147, 154, 161, 168, 175, 182, 189]])