In [2]:
import numpy as np

In [2]:
a = np.zeros(3)

In [3]:
a

array([0., 0., 0.])

In [4]:
type(a)

numpy.ndarray

In [29]:
a = np.ones((4,5,3))
print(a.T.shape)
a = np.floor(10*np.random.random((3,4)))
print(a)

(3, 5, 4)
[[0. 6. 8. 5.]
 [0. 8. 4. 8.]
 [8. 8. 7. 1.]]


In [43]:
def mat(n):
    ret = np.arange(2, n+2, 1)
    for i in range(1, n):
        tmp = np.arange(2, n+2, 1)
        tmp += i
        ret = np.vstack((ret, tmp))
    return np.sin(ret)
np.linalg.det(mat(3))

-8.494842620824162e-17

In [10]:
b = np.random.random((4, 4, 3))
print(b)
#print(b * [0, 1, 1])
c = b.T
c[0] *= 0
print(c.T)

[[[0.22163    0.56397798 0.51889627]
  [0.35344946 0.91259537 0.7831207 ]
  [0.34226994 0.99375776 0.98266259]
  [0.91472113 0.6946419  0.90019873]]

 [[0.50804138 0.83322357 0.24753943]
  [0.68040563 0.20922316 0.96180657]
  [0.79343135 0.23875182 0.95990027]
  [0.53087301 0.43498326 0.69569669]]

 [[0.64519865 0.8984017  0.60234422]
  [0.33165848 0.36131434 0.08728744]
  [0.74633227 0.51646522 0.44240583]
  [0.97824882 0.58178182 0.28241009]]

 [[0.30795047 0.27525321 0.21248003]
  [0.79703423 0.33782183 0.88318138]
  [0.2580018  0.56652543 0.48698822]
  [0.90060013 0.27556447 0.60549407]]]
[[[0.         0.56397798 0.51889627]
  [0.         0.91259537 0.7831207 ]
  [0.         0.99375776 0.98266259]
  [0.         0.6946419  0.90019873]]

 [[0.         0.83322357 0.24753943]
  [0.         0.20922316 0.96180657]
  [0.         0.23875182 0.95990027]
  [0.         0.43498326 0.69569669]]

 [[0.         0.8984017  0.60234422]
  [0.         0.36131434 0.08728744]
  [0.         0.51646522 0